name : churn_classification_CICD_pipeline
  
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  Continuous-Integration:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup python 3.10
      uses: actions/setup-python@v3
      with :
        python-version: "3.10"
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req_dock.txt


  Continuous-Delievery:
    runs-on: ubuntu-latest
    needs: Continuous-Integration   

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          IMAGE_TAG=churn_classifier_2
          docker build -t ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:${IMAGE_TAG} .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin \
            ${{ secrets.AWS_ECR_LOGIN_URI }}

      - name: Push image to ECR
        run: |
          IMAGE_TAG=churn_classifier_2
          docker push ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:${IMAGE_TAG}


  Continuous-Deployment:
    needs: Continuous-Delievery
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pre-pull Docker cleanup
        run: |
            docker rm -f zealous_ardinghelli || true
            docker container prune -f
            docker image prune -f
            docker builder prune -f

      - name: Pull latest images
        run: |
          IMAGE_TAG=churn_classifier_2
          docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:${IMAGE_TAG}


      - name: Run Docker Image
        run: |
                IMAGE_TAG=churn_classifier_2
                docker rm -f zealous_ardinghelli || true
                docker run -d -p 8080:8000 --ipc="host" --name=zealous_ardinghelli \
                  -e 'AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}}' \
                  -e 'AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
                  -e 'AWS_REGION=${{ secrets.AWS_REGION }}' \
                  ${{secrets.AWS_ECR_LOGIN_URI}}/${{ secrets.ECR_REPOSITORY_NAME }}:${IMAGE_TAG}
      - name: Cleanup dangling images & containers
        run: |
            docker container prune -f
            docker image prune -f